name: Accessibility (WCAG) Audit

on:
  workflow_dispatch:
  repository_dispatch:
    types: [wcag]

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ§  Install axe CLI
        run: npm install -g @axe-core/cli

      - name: ğŸ§ª Run accessibility tests
        run: |
          mkdir -p reports
          npx browser-driver-manager install chrome
          npx axe https://next.ssrengineering.tech \
          --save reports/axe-report.json \
          --timeout 60000
        env:
          NODE_ENV: test

      - name: ğŸ“‹ Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: axe-accessibility-report
          path: reports/axe-report.json

      - name: ğŸ“¡ Send results to New Relic
        if: always()
        env:
          NEWRELIC_INSERT_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }} # INSERT KEY = LICENSE KEY
          NEWRELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        run: |
          node .github/scripts/sendToNewRelic.js
